print("enter your name =")
name= input()
print("enter you father name =")
fname= input()
print("enter you University name =")
uni= input()
print("enter you department name =")
dep= input()
print("Enter the section =")
sec= input()
print("enter you roll number =")
rollno= input()

print("The name of student is :" , name)
print("The name of student's father is :" , fname)
print("The student is currently studying in :" , uni)
print("Alloted department of the student is :" , dep)
print("Alloted section of the student is :" , sec)
print("The student's roll number in class is :" , rollno)
print("Congratulations ! Admission Successful ")
